### ISSUE TITLE
float pointer error

### ISSUE THREAD

**Issue by Hokins-Liu** [cbor/cbor.github.io#16]
I use [http://cbor.me/] to verify my cbor f/w , and i found a issue about float point to cbor...

the pattern is:

> BF455465737432FA3FB5E354FF

the ideal output might be:

> {h'5465737432': 1.421000}

but actually output as:

> {h'5465737432': 1.4210000038146973}

the float point to hex data is reference this link:
[http://gregstoll.dyndns.org/~gregstoll/floattohex/]

**Comment by cabo** [comment]
Thank you for reporting a result that you did not expect.

In this case, however, the result is what is intended: The binary32 (32-bit floating point) number 0x3FB5E354 is indeed the closest 32-bit approximation to 1.421:

```
>> "%#0x" % [1.421].pack("g").unpack("N")[0]
=> "0x3fb5e354"
```

However, it is not exactly 1.421 (1421/1000 is a rather odd value in the binary system).  

```
[0x3FB5E354].pack("N").unpack("g")
=> [1.4210000038146973]
```

Internally, Ruby uses a binary64 to represent this value, extending the mantissa of the binary32 value by 29 zero bits.  This does not change the value, but it does change the apparent precision.  Then, when the value is printed out, the binary-to-decimal conversion in sprintf does not know that the actual precision is only that of a binary32, so it prints the decimal value closest to the zero-extended binary value:

```
>> [1.421].pack("g").unpack("g")
=> [1.4210000038146973]
```

Theoretically, I could annotate decoded floating point values by the precision that was given and write additional binary-to-decimal converters that honor the specific precision.  But users of floating point numbers are used to the effects of limited precision, so that effort would be pretty much wasted.

More information at:

[What every programmer should know about floating point](http://floating-point-gui.de)
